# Generated by Django 6.0.1 on 2026-02-15 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(editable=False, max_length=8, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to='inscriptions.inscription')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='payments.paymentagent')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(help_text='Montant payé en FCFA')),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('orange_money', 'Orange Money'), ('bank_transfer', 'Virement bancaire')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='payments/receipts/')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inscriptions.inscription')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentagent')),
            ],
            options={
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['paid_at'], name='payments_pa_paid_at_b40014_idx')],
            },
        ),
    ]
