# Generated by Django 6.0.1 on 2026-03-14 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inscriptions', '0004_inscription_archived_at_inscription_is_archived'),
        ('payments', '0002_paymentagent_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentagent',
            name='agent_code',
            field=models.CharField(db_index=True, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentagent',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_agents', to='branches.branch'),
        ),
        migrations.AddIndex(
            model_name='cashpaymentsession',
            index=models.Index(fields=['expires_at'], name='payments_ca_expires_cf663f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method'], name='payments_pa_method_70cfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentagent',
            index=models.Index(fields=['branch'], name='payments_pa_branch__b79dc3_idx'),
        ),
    ]
