# Generated by Django 6.0.1 on 2026-03-15 14:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inscriptions', '0005_alter_statushistory_options_inscription_updated_at_and_more'),
        ('payments', '0003_alter_payment_amount_alter_payment_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashpaymentsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentagent',
            options={'ordering': ['user__last_name']},
        ),
        migrations.AlterField(
            model_name='cashpaymentsession',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cashpaymentsession',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentagent',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_agents', to='branches.branch'),
        ),
        migrations.AddIndex(
            model_name='cashpaymentsession',
            index=models.Index(fields=['is_used'], name='payments_ca_is_used_467e71_idx'),
        ),
        migrations.AddIndex(
            model_name='cashpaymentsession',
            index=models.Index(fields=['agent', 'created_at'], name='payments_ca_agent_i_12e9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'paid_at'], name='payments_pa_status_bed4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method', 'paid_at'], name='payments_pa_method_13c640_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['inscription', 'status'], name='payments_pa_inscrip_eee98f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentagent',
            index=models.Index(fields=['is_active'], name='payments_pa_is_acti_8543e1_idx'),
        ),
    ]
