# Generated by Django 6.0.1 on 2026-02-15 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Étudiant actif dans l’établissement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='inscriptions.inscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
