# Generated by Django 6.0.1 on 2026-02-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_program_news_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='news',
            name='news_news_status_b581f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='news',
            name='news_news_publish_377f0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='news',
            name='news_news_slug_915ecd_idx',
        ),
        migrations.AddField(
            model_name='news',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
