# Generated by Django 6.0.1 on 2026-02-24 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('semestre', 'Résultat semestriel'), ('examen', 'Examen national')], max_length=20)),
                ('annee_academique', models.CharField(max_length=20)),
                ('annexe', models.CharField(max_length=150)),
                ('filiere', models.CharField(max_length=150)),
                ('classe', models.CharField(max_length=150)),
                ('fichier_pdf', models.FileField(upload_to='resultats/pdf/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_session', to='news.news')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
