# Generated by Django 6.0.1 on 2026-02-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_resultsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultsession',
            options={'ordering': ['-annee_academique', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='resultsession',
            name='news',
        ),
        migrations.AddField(
            model_name='resultsession',
            name='titre',
            field=models.CharField(default='Résultat académique', max_length=255),
            preserve_default=False,
        ),
    ]
