# Generated by Django 6.0.1 on 2026-02-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_eventtype_event_mediaitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='news_event_event_d_fdbd26_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='news_event_slug_d2d236_idx',
        ),
        migrations.RemoveIndex(
            model_name='mediaitem',
            name='news_mediai_media_t_32e58a_idx',
        ),
        migrations.RemoveIndex(
            model_name='mediaitem',
            name='news_mediai_created_6b847c_idx',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='events/videos/'),
        ),
    ]
