# Generated by Django 6.0.1 on 2026-03-01 13:15


import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(blank=True, choices=[('identity', 'Identité de l’école'), ('vision', 'Vision & Mission'), ('governance', 'Gouvernance'), ('infrastructure', 'Infrastructures'), ('student_life', 'Vie étudiante'), ('network', 'Annexes & Partenariats')], max_length=50, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),

                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('highlights', models.JSONField(blank=True, help_text="Liste des points clés (ex: ['Reconnu par l’État', 'Système LMD'])", null=True)),
                ('icon', models.CharField(blank=True, help_text='Classe icône (ex: fa-solid fa-graduation-cap)', max_length=100, null=True)),
                ('background', models.CharField(default='white', help_text='white | light | primary', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section À propos',
                'verbose_name_plural': 'Sections À propos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Mali', max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('legal_status', models.CharField(blank=True, max_length=255)),
                ('approval_number', models.CharField(blank=True, max_length=255)),
                ('director_title', models.CharField(default='Direction Générale', max_length=255)),
                ('hosting_provider', models.CharField(blank=True, max_length=255)),
                ('hosting_location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institution',
            },
        ),
        migrations.CreateModel(
            name='InstitutionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('legal', 'Mentions légales'), ('privacy', 'Politique de confidentialité'), ('terms', 'Conditions d’utilisation')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),

                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('review', 'En révision'), ('published', 'Publié')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page légale',
                'verbose_name_plural': 'Pages légales',
                'ordering': ['page_type'],
            },
        ),
        migrations.CreateModel(
            name='LegalPageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('content_snapshot', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.legalpage')),
            ],
            options={
                'verbose_name': 'Historique de page',
                'verbose_name_plural': 'Historique des pages',
            },
        ),
        migrations.CreateModel(
            name='LegalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),

                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.legalpage')),
            ],
            options={
                'verbose_name': 'Section légale',
                'verbose_name_plural': 'Sections légales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LegalSidebarBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),

                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_blocks', to='core.legalpage')),
            ],
            options={
                'verbose_name': 'Bloc sidebar légal',
                'verbose_name_plural': 'Blocs sidebar légaux',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(choices=[('admission', 'Admission'), ('formation', 'Information formation'), ('inscription', 'Inscription administrative'), ('payment', 'Paiement'), ('partnership', 'Partenariat'), ('complaint', 'Réclamation'), ('other', 'Autre')], max_length=50)),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('sla_hours', models.PositiveIntegerField(default=48)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('answered', 'Répondu'), ('closed', 'Clôturé')], default='new', max_length=20)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_contac_status_de41ec_idx'), models.Index(fields=['priority'], name='core_contac_priorit_5f9b6e_idx'), models.Index(fields=['created_at'], name='core_contac_created_63cb1b_idx')],
            },
        ),
    ]
