# Generated by Django 6.0.1 on 2026-03-03 09:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='introduction',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='legalsection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Contenu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalsidebarblock',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Contenu'),
            preserve_default=False,
        ),
    ]
