# Generated by Django 6.0.1 on 2026-03-11 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_statushistory_notification'),
        ('formations', '0005_competenceblock_competenceitem_programmetab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du partenaire', max_length=200)),
                ('logo', models.ImageField(help_text='Logo du partenaire', upload_to='partners/logos/')),
                ('website', models.URLField(blank=True, help_text='Site web du partenaire')),
                ('description', models.TextField(blank=True, help_text='Description du partenariat')),
                ('partner_type', models.CharField(choices=[('ministere', 'Ministère'), ('hospital', 'Centre Hospitalier'), ('international', 'Organisation Internationale'), ('ong', 'ONG'), ('entreprise', 'Entreprise'), ('university', 'Université'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, help_text='URL YouTube ou Vimeo (ex: https://youtube.com/watch?v=...)')),
                ('video_thumbnail', models.ImageField(blank=True, help_text='Image de prévisualisation si pas de vidéo', null=True, upload_to='temoignages/thumbnails/')),
                ('quote', models.TextField(help_text='Le témoignage en quelques phrases')),
                ('author_name', models.CharField(help_text='Nom complet du diplômé', max_length=150)),
                ('author_role', models.CharField(blank=True, help_text='Poste actuel (ex: Directeur des ressources humaines)', max_length=200)),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='temoignages/photos/')),
                ('promotion', models.CharField(blank=True, help_text='Année de promotion (ex: Promo 2019)', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text="Afficher en priorité sur la page d'accueil")),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('programme', models.ForeignKey(blank=True, help_text='Formation suivie (laisser vide pour témoignage global)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='formations.programme')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-is_featured', 'order', '-pk'],
            },
        ),
    ]
