# Generated by Django 6.0.1 on 2026-03-20 07:59

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_partner_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Laboratoire de biologie', max_length=150, verbose_name='Nom')),
                ('category', models.CharField(choices=[('laboratory', 'Laboratoire'), ('classroom', 'Salle de cours'), ('equipment', 'Équipement'), ('library', 'Bibliothèque'), ('sports', 'Infrastructure sportive'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(help_text='Description détaillée', verbose_name='Description')),
                ('image', models.ImageField(upload_to='infrastructure/', verbose_name='Photo')),
                ('features', models.JSONField(blank=True, help_text="Liste des équipements (ex: ['Microscopes', 'Analyseurs'])", null=True, verbose_name='Caractéristiques')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Infrastructure',
                'verbose_name_plural': 'Infrastructures',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='À propos de notre institution', max_length=255, verbose_name='Titre présentation')),
                ('about_text', django_ckeditor_5.fields.CKEditor5Field(help_text="Description générale de l'école (2-3 paragraphes)", verbose_name='Texte de présentation')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='institution/', verbose_name='Image présentation')),
                ('vision_title', models.CharField(default='Notre Vision', max_length=255, verbose_name='Titre vision')),
                ('vision_text', models.TextField(help_text="La vision à long terme de l'institution", verbose_name='Vision')),
                ('mission_title', models.CharField(default='Notre Mission', max_length=255, verbose_name='Titre mission')),
                ('mission_text', models.TextField(help_text="La mission quotidienne de l'institution", verbose_name='Mission')),
                ('hero_title', models.CharField(default='Former les professionnels de santé de demain', max_length=255, verbose_name='Titre Hero')),
                ('hero_subtitle', models.CharField(default="Une institution d'excellence dédiée à la formation paramédicale et scientifique.", max_length=500, verbose_name='Sous-titre Hero')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='institution/hero/', verbose_name='Image Hero (background)')),
                ('cta_title', models.CharField(default="Rejoignez une institution d'excellence", max_length=255, verbose_name='Titre CTA')),
                ('cta_subtitle', models.CharField(blank=True, default='Commencez votre parcours vers une carrière dans les sciences de la santé.', max_length=500, verbose_name='Sous-titre CTA')),
                ('cta_button_text', models.CharField(default='Candidater maintenant', max_length=100, verbose_name='Texte bouton CTA')),
                ('cta_button_url', models.CharField(default='/candidature/', max_length=255, verbose_name='URL bouton CTA')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Présentation',
                'verbose_name_plural': 'Présentation',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('position', models.CharField(help_text='Ex: Directeur Général, Professeur de Biologie', max_length=200, verbose_name='Poste')),
                ('category', models.CharField(choices=[('direction', 'Direction'), ('teacher', 'Enseignant'), ('admin', 'Administration')], default='teacher', max_length=20, verbose_name='Catégorie')),
                ('photo', models.ImageField(help_text='Photo professionnelle (format carré recommandé)', upload_to='staff/', verbose_name='Photo')),
                ('bio', models.TextField(blank=True, help_text='Courte bio (optionnel)', verbose_name='Biographie')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
                ('linkedin', models.URLField(blank=True, verbose_name='Profil LinkedIn')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Afficher en priorité', verbose_name='Mis en avant')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['category', 'order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Excellence, Engagement, Innovation', max_length=100, verbose_name='Titre')),
                ('description', models.TextField(help_text='Description courte (1-2 phrases)', verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Classe CSS icône (ex: fa-solid fa-graduation-cap)', max_length=100, verbose_name='Icône')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Valeur',
                'verbose_name_plural': 'Valeurs',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.AddField(
            model_name='institutionstat',
            name='prefix',
            field=models.CharField(blank=True, help_text='Ex: +', max_length=10, verbose_name='Préfixe'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='approval_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='N° agrément'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.CharField(default='Mali', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='legal_status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Statut juridique'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom court'),
        ),
        migrations.AlterField(
            model_name='institutionstat',
            name='label',
            field=models.CharField(help_text='Ex: Étudiants formés', max_length=100, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='institutionstat',
            name='suffix',
            field=models.CharField(blank=True, help_text='Ex: +, %, ans', max_length=10, verbose_name='Suffixe'),
        ),
        migrations.AlterField(
            model_name='institutionstat',
            name='value',
            field=models.PositiveIntegerField(help_text='Ex: 500', verbose_name='Valeur'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='page_type',
            field=models.CharField(choices=[('legal', 'Mentions légales'), ('privacy', 'Politique de confidentialité'), ('terms', "Conditions d'utilisation")], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('candidature_submitted', 'Candidature soumise'), ('candidature_under_review', "Candidature en cours d'analyse"), ('candidature_to_complete', 'Candidature à compléter'), ('candidature_accepted', 'Candidature acceptée'), ('candidature_accepted_with_reserve', 'Candidature acceptée sous réserve'), ('candidature_rejected', 'Candidature refusée'), ('inscription_created', 'Inscription créée'), ('inscription_active', 'Inscription active'), ('payment_received', 'Paiement reçu'), ('payment_validated', 'Paiement validé'), ('document_missing', 'Document manquant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description du partenariat'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom du partenaire'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('ministere', 'Ministère'), ('hospital', 'Centre Hospitalier'), ('international', 'Organisation Internationale'), ('ong', 'ONG'), ('entreprise', 'Entreprise'), ('university', 'Université'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
    ]
