# Generated by Django 6.0.1 on 2026-02-15 14:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_token', models.CharField(db_index=True, editable=False, max_length=60, unique=True)),
                ('access_code', models.CharField(blank=True, editable=False, help_text='Code d’accès privé au dossier', max_length=32)),
                ('status', models.CharField(choices=[('created', 'Créée'), ('active', 'Active'), ('suspended', 'Suspendue')], db_index=True, default='created', max_length=20)),
                ('amount_due', models.PositiveBigIntegerField(help_text='Montant total à payer (FCFA)')),
                ('amount_paid', models.PositiveBigIntegerField(default=0, editable=False, help_text='Montant payé (calcul automatique)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inscription', to='admissions.candidature')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
