# Generated by Django 6.0.1 on 2026-03-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='status',
            field=models.CharField(choices=[('created', 'Créée'), ('awaiting_payment', 'En attente paiement'), ('partial_paid', 'Paiement partiel'), ('active', 'Active'), ('suspended', 'Suspendue'), ('cancelled', 'Annulée'), ('completed', 'Terminée'), ('expired', 'Expirée')], db_index=True, default='created', max_length=20),
        ),
    ]
