# Generated by Django 6.0.1 on 2026-03-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_statushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
