# Generated by Django 6.0.1 on 2026-03-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_candidature_academic_year_and_more'),
        ('inscriptions', '0004_inscription_archived_at_inscription_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statushistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='inscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['status'], name='inscription_status_7d65c3_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['created_at'], name='inscription_created_e430e6_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['is_archived'], name='inscription_is_arch_64b9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['status', 'created_at'], name='inscription_status_745b93_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['status', 'amount_paid'], name='inscription_status_c478eb_idx'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['created_at'], name='inscription_created_5f1bab_idx'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['inscription', 'created_at'], name='inscription_inscrip_e68d56_idx'),
        ),
    ]
