# Generated by Django 6.0.1 on 2026-03-13 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Annexe choisie pour l'inscription", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='branches.branch', verbose_name='Annexe'),
        ),
    ]
