# Generated by Django 6.0.1 on 2026-03-15 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_candidature_branch'),
        ('branches', '0001_initial'),
        ('formations', '0006_programme_updated_at_alter_cycle_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='academic_year',
            field=models.CharField(db_index=True, help_text='Année académique (ex: 2025-2026)', max_length=9),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='branch',
            field=models.ForeignKey(help_text="Annexe choisie pour l'inscription", on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='branches.branch', verbose_name='Annexe'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='candidaturedocument',
            name='is_valid',
            field=models.BooleanField(db_index=True, default=False, help_text='Validé par l’administration'),
        ),
        migrations.AlterField(
            model_name='candidaturedocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['branch'], name='admissions__branch__728fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['submitted_at'], name='admissions__submitt_7cf215_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['branch', 'status'], name='admissions__branch__140cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['branch', 'submitted_at'], name='admissions__branch__b8b6c1_idx'),
        ),
        migrations.AddIndex(
            model_name='candidaturedocument',
            index=models.Index(fields=['uploaded_at'], name='admissions__uploade_02e24d_idx'),
        ),
        migrations.AddIndex(
            model_name='candidaturedocument',
            index=models.Index(fields=['candidature', 'is_valid'], name='admissions__candida_0bbfdf_idx'),
        ),
    ]
