# Generated by Django 6.0.1 on 2026-03-16 11:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_candidature_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='completion_message',
            field=models.TextField(blank=True, help_text='Message envoyé au candidat pour compléter son dossier', verbose_name='Message de complétion'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_candidatures', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='candidature',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Raison du refus de la candidature', verbose_name='Motif de refus'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_candidatures', to=settings.AUTH_USER_MODEL, verbose_name='Révisé par'),
        ),
        migrations.AddField(
            model_name='candidaturedocument',
            name='is_validated',
            field=models.BooleanField(db_index=True, default=False, help_text='Document validé'),
        ),
        migrations.AddField(
            model_name='candidaturedocument',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='candidaturedocument',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_documents', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='entry_year',
            field=models.PositiveSmallIntegerField(default=1, help_text="Année d'entrée dans le programme", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de révision'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='status',
            field=models.CharField(choices=[('submitted', 'Soumise'), ('under_review', "En cours d'analyse"), ('to_complete', 'À compléter'), ('accepted', 'Acceptée'), ('accepted_with_reserve', 'Acceptée sous réserve'), ('rejected', 'Refusée')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidaturedocument',
            name='is_valid',
            field=models.BooleanField(db_index=True, default=False, help_text="Validé par l'administration"),
        ),
    ]
