# Generated by Django 6.0.1 on 2026-03-02 14:34

import community.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_answers', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.answer')),
            ],
            options={
                'ordering': ['-upvotes', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='community_c_slug_777ae5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='community/topics/%Y/%m/')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_topics', to='community.answer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_topics', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='community.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='topics', to='community.tag')),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=community.models.attachment_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='community.answer')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='community.topic')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='community.topic'),
        ),
        migrations.CreateModel(
            name='TopicView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.topic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['slug'], name='community_t_slug_3988f7_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['created_at'], name='community_t_created_122fea_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['category'], name='community_t_categor_65a2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_published'], name='community_t_is_publ_13d760_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['last_activity_at'], name='community_t_last_ac_c6a991_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['topic'], name='community_a_topic_i_7c1764_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['answer'], name='community_a_answer__633eac_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['topic'], name='community_a_topic_i_41db57_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['parent'], name='community_a_parent__f4598b_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['created_at'], name='community_a_created_0d72f3_idx'),
        ),
        migrations.AddIndex(
            model_name='topicview',
            index=models.Index(fields=['topic'], name='community_t_topic_i_17974a_idx'),
        ),
        migrations.AddIndex(
            model_name='topicview',
            index=models.Index(fields=['user'], name='community_t_user_id_5a5d91_idx'),
        ),
        migrations.AddIndex(
            model_name='topicview',
            index=models.Index(fields=['ip_address'], name='community_t_ip_addr_bed989_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['answer'], name='community_v_answer__1a2700_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user'], name='community_v_user_id_35388e_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'answer'), name='unique_user_answer_vote'),
        ),
    ]
