# Generated by Django 6.0.1 on 2026-03-02 17:54

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_topic_is_deleted_topic_is_edited_topic_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenu'),
        ),
    ]
