# Generated by Django 6.0.1 on 2026-03-04 22:07

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='Couleur associée (ex: #4CAF50)', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Nom de l'icône (ex: bi-flask, bi-heart-pulse)", max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs abonnés à ce domaine', related_name='subscribed_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la liste des catégories"),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='community_c_is_acti_45d009_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['order'], name='community_c_order_765592_idx'),
        ),
    ]
