# Generated by Django 6.0.1 on 2026-03-06 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_category_color_category_created_at_category_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='community_n_user_id_12ced1_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Date de lecture de la notification', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='vote_count',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de votes agrupés (pour les notifications de type upvote)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(help_text="L'utilisateur qui a déclenché la notification", on_delete=django.db.models.deletion.CASCADE, related_name='performed_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.answer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_topic', 'Nouveau sujet dans votre domaine'), ('new_answer', 'Nouvelle réponse à votre sujet'), ('reply_to_reply', 'Réponse à votre commentaire'), ('upvote', 'Nouveau(x) vote(s) sur votre contribution'), ('accepted_answer', 'Votre réponse a été acceptée')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.topic'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='community_n_user_id_bfc574_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type'], name='community_n_user_id_309438_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['topic'], name='community_n_topic_i_f8861d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['answer'], name='community_n_answer__0dab9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'topic', 'answer', 'notification_type'), name='unique_notification'),
        ),
    ]
