# Generated by Django 6.0.1 on 2026-03-04 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_badge_bronze_profile_badge_gold_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-reputation'], 'verbose_name': 'Profil', 'verbose_name_plural': 'Profils'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='main_domain',
            field=models.CharField(blank=True, db_index=True, help_text="Domaine principal d'activité", max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_topics',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
