# Generated by Django 6.0.1 on 2026-03-14 16:08

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_options_alter_profile_created_at_and_more'),
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_profiles', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Administrateur'), ('executive', 'Direction'), ('admissions', 'Admissions'), ('finance', 'Finance'), ('teacher', 'Enseignant'), ('student', 'Étudiant')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_upload_path, validators=[accounts.models.validate_avatar_extension]),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role'], name='accounts_pr_role_fae1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['branch'], name='accounts_pr_branch__0d3d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['reputation'], name='accounts_pr_reputat_9c846e_idx'),
        ),
    ]
