# Generated by Django 6.0.1 on 2026-03-21 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_branch_profile_role_alter_profile_avatar_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, help_text="École à laquelle l'utilisateur est rattaché", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='schools.school', verbose_name='École'),
        ),
    ]
