# Generated by Django 6.0.1 on 2026-03-13 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name="Nom de l'annexe")),
                ('code', models.CharField(help_text='Code court (ex: KC, BC, KT)', max_length=10, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(default='Bamako', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_online_registration', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annexe',
                'verbose_name_plural': 'Annexes',
                'ordering': ['name'],
            },
        ),
    ]
