# Generated by Django 6.0.1 on 2026-02-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_approved_at_comment_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
