# Generated by Django 6.0.1 on 2026-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_commentlike_options_commentlike_reaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_status_74f07c_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_flagged_52a2a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_created_4e025c_idx',
        ),
        migrations.RemoveIndex(
            model_name='commentlike',
            name='blog_commen_comment_a06024_idx',
        ),
        migrations.AlterField(
            model_name='comment',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
