# Generated by Django 6.0.1 on 2026-02-25 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_blog_commen_status_74f07c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('comment', 'user'), name='unique_user_reaction_per_comment'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('comment', 'ip_address'), name='unique_ip_reaction_per_comment'),
        ),
    ]
