# Generated by Django 6.0.1 on 2026-03-21 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: École des Sciences Médicales Félix Houphouët-Boigny', max_length=200, unique=True, verbose_name="Nom de l'école")),
                ('short_name', models.CharField(help_text='Ex: EsMed, ESGA, FATEC', max_length=20, unique=True, verbose_name='Nom court')),
                ('code', models.CharField(help_text='Code unique (ex: ESMED, ESGA, FATEC)', max_length=10, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, help_text="Présentation de l'école", verbose_name='Description')),
                ('mission', models.TextField(blank=True, help_text="Mission et objectifs de l'école", verbose_name='Mission')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/', verbose_name="Logo de l'école")),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='schools/covers/', verbose_name='Image de couverture')),
                ('primary_color', models.CharField(default='#1E3A8A', help_text='Couleur principale HEX (ex: #1E3A8A)', max_length=7)),
                ('secondary_color', models.CharField(default='#F97316', help_text='Couleur secondaire HEX (ex: #F97316)', max_length=7)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name="Email de l'école")),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('accepts_online_applications', models.BooleanField(default=True, verbose_name='Accepte les candidatures en ligne')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_schools', to=settings.AUTH_USER_MODEL, verbose_name='Directeur')),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
                'ordering': ['order', 'name'],
            },
        ),
    ]
