# Generated by Django 6.0.1 on 2026-02-15 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_duration_years', models.PositiveSmallIntegerField()),
                ('max_duration_years', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_duration_years'],
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('level', models.CharField(choices=[('secondaire', 'Secondaire'), ('superieur', 'Supérieur')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('duration_years', models.PositiveSmallIntegerField()),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='formations.cycle')),
                ('diploma_awarded', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='formations.diploma')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='formations.filiere')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.PositiveSmallIntegerField()),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='formations.programme')),
            ],
            options={
                'ordering': ['year_number'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('due_month', models.CharField(max_length=50)),
                ('programme_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='formations.programmeyear')),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeRequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='formations.programme')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formations.requireddocument')),
            ],
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['is_active'], name='formations__is_acti_0a3e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['is_featured'], name='formations__is_feat_4b661a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programmeyear',
            unique_together={('programme', 'year_number')},
        ),
        migrations.AlterUniqueTogether(
            name='fee',
            unique_together={('programme_year', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='programmerequireddocument',
            unique_together={('programme', 'document')},
        ),
    ]
