# Generated by Django 6.0.1 on 2026-02-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='career_opportunities',
            field=models.TextField(blank=True, help_text='Métiers et secteurs accessibles après la formation'),
        ),
        migrations.AddField(
            model_name='programme',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='programmes/illustrations/'),
        ),
        migrations.AddField(
            model_name='programme',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='Compétences et savoir-faire développés durant la formation'),
        ),
        migrations.AddField(
            model_name='programme',
            name='program_structure',
            field=models.TextField(blank=True, help_text='Organisation pédagogique : cours, stages, travaux pratiques, etc.'),
        ),
    ]
