# Generated by Django 6.0.1 on 2026-02-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_programme_career_opportunities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='theme',
            field=models.CharField(choices=[('primary', 'Bleu institutionnel'), ('secondary', 'Orange premium'), ('dark', 'Sombre (Doctorat)')], default='primary', max_length=20),
        ),
    ]
