# Generated by Django 6.0.1 on 2026-02-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_cycle_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='theme',
            field=models.CharField(choices=[('accent', 'Bleu institutionnel'), ('secondary', 'Orange premium'), ('dark', 'Sombre (Doctorat)')], default='primary', max_length=20),
        ),
    ]
