# Generated by Django 6.0.1 on 2026-03-10 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_alter_cycle_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence_blocks', to='formations.programme')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='formations.competenceblock')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_type', models.CharField(choices=[('key_info', 'Infos clés'), ('program', 'Programme'), ('careers', 'Débouchés'), ('admission', 'Admission'), ('custom', 'Personnalisé')], default='custom', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='formations.programme')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('programme', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProgrammeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('text', 'Texte simple'), ('heading', 'Titre + Description'), ('list', 'Liste à puces'), ('cards', 'Cartes/Blocs'), ('cta', "Appel à l'action")], default='text', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='formations.programmetab')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeQuickFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('academic_cap', 'Capacité académique'), ('calendar', 'Calendrier'), ('clock', 'Horloge/Durée'), ('location', 'Localisation'), ('certificate', 'Certification'), ('user', 'Profil étudiant'), ('briefcase', 'Valise/Métier')], default='academic_cap', max_length=30)),
                ('label', models.CharField(help_text='Ex: Niveau, Durée, Rentrée', max_length=100)),
                ('value', models.CharField(help_text='Ex: Bac+5, 2 ans, Septembre 2026', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_facts', to='formations.programme')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('programme', 'icon', 'label')},
            },
        ),
    ]
