# Generated by Django 6.0.1 on 2026-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0005_competenceblock_competenceitem_programmetab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='theme',
            field=models.CharField(choices=[('accent', 'Bleu institutionnel'), ('secondary', 'Orange premium'), ('dark', 'Sombre (Doctorat)')], default='accent', max_length=20),
        ),
    ]
