# Generated by Django 6.0.1 on 2026-03-21 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0006_programme_updated_at_alter_cycle_theme'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competenceblock',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Bloc de compétences', 'verbose_name_plural': 'Blocs de compétences'},
        ),
        migrations.AlterModelOptions(
            name='competenceitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Item de compétence', 'verbose_name_plural': 'Items de compétences'},
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['min_duration_years'], 'verbose_name': 'Cycle', 'verbose_name_plural': 'Cycles'},
        ),
        migrations.AlterModelOptions(
            name='diploma',
            options={'verbose_name': 'Diplôme', 'verbose_name_plural': 'Diplômes'},
        ),
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['amount'], 'verbose_name': 'Frais', 'verbose_name_plural': 'Frais'},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['name'], 'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['title'], 'verbose_name': 'Programme', 'verbose_name_plural': 'Programmes'},
        ),
        migrations.AlterModelOptions(
            name='programmequickfact',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Fait rapide', 'verbose_name_plural': 'Faits rapides'},
        ),
        migrations.AlterModelOptions(
            name='programmerequireddocument',
            options={'verbose_name': 'Document requis pour programme', 'verbose_name_plural': 'Documents requis pour programmes'},
        ),
        migrations.AlterModelOptions(
            name='programmesection',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='programmetab',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Onglet', 'verbose_name_plural': 'Onglets'},
        ),
        migrations.AlterModelOptions(
            name='programmeyear',
            options={'ordering': ['year_number'], 'verbose_name': 'Année de programme', 'verbose_name_plural': 'Années de programme'},
        ),
        migrations.AlterModelOptions(
            name='requireddocument',
            options={'verbose_name': 'Document requis', 'verbose_name_plural': 'Documents requis'},
        ),
        migrations.AddField(
            model_name='programme',
            name='school',
            field=models.ForeignKey(blank=True, help_text='École à laquelle appartient ce programme (EsMed, ESGA, FATEC)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='schools.school', verbose_name='École'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['school'], name='formations__school__b6dd05_idx'),
        ),
    ]
